monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*reSpeaker*"
      }
    ]
    actions = {
      update-props = {
        node.description = "reSpeaker XVF3800 4-Mic Array Analog Stereo"
        # Lock default volume initialization properties if supported by the driver
        audio.volume = 0.13
      }
    }
  }
]

