<?xml version="1.0"?>
<robot name="elsabot_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find elsabot_robot)/urdf/2wd_properties.urdf.xacro" />
  <xacro:include filename="$(find elsabot_robot)/urdf/mech/base.urdf.xacro" />
  <xacro:include filename="$(find elsabot_robot)/urdf/mech/wheel.urdf.xacro" />
  <xacro:include filename="$(find elsabot_robot)/urdf/mech/wheel_steering.urdf.xacro" />
  <xacro:include filename="$(find elsabot_robot)/urdf/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find elsabot_robot)/urdf/sensors/gps.urdf.xacro" />
  <xacro:include filename="$(find elsabot_robot)/urdf/sensors/generic_laser.urdf.xacro" />
  <xacro:include filename="$(find elsabot_robot)/urdf/sensors/oakd_on_ptbase.urdf.xacro" />
  <xacro:include filename="$(find elsabot_robot)/urdf/controllers/ackermann_drive.urdf.xacro" />  

  <xacro:base 
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_z="${wheel_pos_z}"
    mesh="package://elsabot_robot/meshes/ebot.stl"
  />

  <xacro:wheel 
    parent_link="front_left_wheel_steering_link" 
    side="front_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="0" 
    pos_y="${wheel_center_to_kingpin}" 
    pos_z="0" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    parent_link="front_right_wheel_steering_link" 
    side="front_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="0" 
    pos_y="${-wheel_center_to_kingpin}" 
    pos_z="0" 
    mass="${wheel_mass}"
  />
  
  <xacro:wheel 
    parent_link="base_link" 
    side="rear_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x_rear + base_link_x_offset_to_center}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z + base_link_z_offset_to_center}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    parent_link="base_link" 
    side="rear_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x_rear + base_link_x_offset_to_center}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z + base_link_z_offset_to_center}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel_steering
    parent_link="base_link" 
    side="front_left"
    pos_x="${wheel_pos_x_front + base_link_x_offset_to_center}" 
    pos_y="${kingpin_width/2}" 
    pos_z="${wheel_pos_z + base_link_z_offset_to_center}" 
    mass="${wheel_mass_steering}"
    max_steer="${wheel_max_steer}"
  />

  <xacro:wheel_steering
    parent_link="base_link" 
    side="front_right"
    pos_x="${wheel_pos_x_front + base_link_x_offset_to_center}" 
    pos_y="${-kingpin_width/2}" 
    pos_z="${wheel_pos_z + base_link_z_offset_to_center}" 
    mass="${wheel_mass_steering}"
    max_steer="${wheel_max_steer}"
  />
 
  <xacro:generic_laser
    gz_laser_topic="scan"
    gz_base_laser_topic="base_scan">
    <xacro:insert_block name="laser_pose" />
  </xacro:generic_laser>

  <xacro:imu
    gz_imu_topic="ebot/imu/data"
    gz_mag_topic="ebot/imu/mag">
    <xacro:insert_block name="imu_pose"/>
  </xacro:imu>

  <xacro:gps
    gz_gps_topic="gps/fix">
    <xacro:insert_block name="gps_pose"/>
  </xacro:gps>

  <xacro:depth_sensor>
    <xacro:insert_block name="depth_sensor_pose" />
  </xacro:depth_sensor>

  <gazebo>
    <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <plugin filename="gz-sim-magnetometer-system" name="gz::sim::systems::Magnetometer"/>
    <plugin filename="gz-sim-navsat-system" name="gz::sim::systems::NavSat"/>
  </gazebo>

  <xacro:ackermann_drive_controller
    wheel_base = "${wheel_base}"
    wheel_max_steer = "${wheel_max_steer}"
    wheel_separation = "${2*wheel_pos_y}"
    kingpin_width = "${kingpin_width}"
    wheel_radius = "${wheel_radius}"
    gz_odom_topic="/ebot/odom"
    gz_cmd_vel_topic="/cmd_vel/muxed"

  />

</robot>
